name: Dart CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev, 2.12.0, 2.14.1]
    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run core and creator tests
        run: dart test -x webdriver

      - name: Run HTML tests
        run: dart test -t html -p chrome

      - name: Start webdriver
        run: chromedriver --port=4444 --url-base=wd/hub &

      - name: Run webdriver tests
        run: dart test -t webdriver
